
version: '3'
services:
  app:
    container_name: flask
    image: mintproject/dash-viz:latest
    build:
      context: .
      dockerfile: docker/flask/Dockerfile
    ports:
      - 10002:8080
    expose:
      - 8080
