
version: '3'
services:
  web_server:
    container_name: nginx
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - 10000:80
    depends_on:
      - app
  app:
    container_name: flask
    build:
      context: .
      dockerfile: docker/flask/Dockerfile
    ports:
      - 10001:8080
    expose:
      - 8080
